### ISSUE TITLE
ㅠㅠㅠㅠㅠㅠㅠㅠ

### ISSUE THREAD

**Issue by Jackson-Kang** [jyunlee/jyunlee.github.io#1]
nㅠㅠ

**Comment by jyunlee** [comment]
> nㅠㅠ

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 시간 보니까 딱 미팅 끝나고 해탈해있을 시간이네여,,

**Comment by Jackson-Kang** [comment]
ㅠㅠㅠㅠㅠㅠㅠㅠ 화요일인데여 미팅

**Comment by DonghweeYoon** [comment]
ㅋㅋ 방명록 남기고 감

**Comment by jyunlee** [comment]
@DonghweeYoon 아니 방명록을 여기다가 남기시다니 ㅎㅎ 잘 지내고 있죠 오빠?! :)

**Comment by DonghweeYoon** [comment]
@jyunlee 논문 준비하느라 되게 빡시네 ㅋㅋ GAN 쪽 연구는 잘 되가니 :)
